version: '3.8'

volumes:
  fd_data:
  static_value:
  media_value:
  redoc:

services:
  db:
    image: postgres:13.10
    volumes:
      - fd_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  backend:
    image: skogoreveduard/infra_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ../.env

  frontend:
    image: skogoreveduard/infra_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: skogoreveduard/infra_gateway
    ports:
      - "8080:80"
    volumes:
      #- ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
